package com.revolut.mts.dao.impl;

import com.revolut.mts.dao.InitialSetupDao;
import com.revolut.mts.exception.DatabaseException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Consists the implementations of dao operations related to the initial setup
 *
 * @author iasa0862 18/07/19
 */
public class InitialSetupDaoImpl implements InitialSetupDao {

    private static final Logger LOGGER = LoggerFactory.getLogger(InitialSetupDaoImpl.class);

    @Override
    public void createUserAccountTable(Connection connection) {
        try {
            PreparedStatement statement = connection.prepareStatement("CREATE TABLE user_accounts (account_number BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 10000000)," +
                    " account_holder VARCHAR(250), balance DECIMAL(10,2) NOT NULL DEFAULT 0, CONSTRAINT chk_balance CHECK (balance >= 0), PRIMARY KEY (account_number)) AUTO_INCREMENT=100000");
            statement.execute();

            statement.close();
            connection.close();
        } catch (SQLException e) {
            LOGGER.error("Error occurred when creating user account table", e);
            throw new DatabaseException("Error occurred when creating transaction table");
        }
    }

    @Override
    public void createTransactionTable(Connection connection) {
        try {
            PreparedStatement statement = connection.prepareStatement("CREATE TABLE transactions (transaction_id INT NOT NULL AUTO_INCREMENT, status VARCHAR(20), " +
                    "sender INTEGER(10) NOT NULL, receiver INTEGER(10) NOT NULL, amount DECIMAL(10,2) NOT NULL DEFAULT 0, CONSTRAINT chk_amount CHECK (amount > 0), PRIMARY KEY (transaction_id))");
            statement.execute();

            statement.close();
            connection.close();
        } catch (SQLException e) {
            LOGGER.error("Error occurred when creating transaction table", e);
            throw new DatabaseException("Error occurred when creating transaction table");
        }
    }
}
